Algoritmo "ativ7"
// Disciplina   : Programação e algoritmos
// Professor   : Anderson Vanin
// Autor(a)    : Gustavo Bispo Nogueira
// Data atual  : 17/08/2021

Var
x, soma, valor: inteiro

Inicio

escreval("Digite um valor")
leia (valor)
para x de 1 ate valor faca
  escreval("Valor do contador ->",x)
  soma<-soma+x
fimpara

escreval ("O valor acumulado é: ",soma)

Fimalgoritmo