Algoritmo "ativ10"
// Disciplina   : Programação e algoritmos
// Professor   : Anderson Vanin
// Autor(a)    : Gustavo Bispo Nogueira
// Data atual  : 17/08/2021

Var

fatorial, x, num:inteiro

Inicio

escreval ("Digite um número: ")
leia (num)

x <- 1
fatorial <- 1

enquanto x <= num faca
  fatorial <- fatorial * x
  x <- x +1
fimenquanto

escreval ("Seu fatorial é: ",fatorial)
Fimalgoritmo